<section class="section">
    <div class="section__header">
        <h2 class="section__title">У вас интересный проект? Напишите мне</h2>
    </div>

    <div class="section__body">
        <div id="feedback" class="feedback">
            <div id="feedbackMsg"></div>
            <form id="feedbackForm" action="/feedback/send" class="form" method="post">
                <div class="form__group clearfix disable-float">
                    <div class="form__col">
                        <label class="form__label" for="name">Имя</label>

                        <div class="form__input-section">
                            <input type="text" id="name" name="name" class="form__input"
                                   placeholder="Как к Вам обращаться"/>
                        </div>
                    </div>
                    <div class="form__col disable-margin">
                        <label class="form__label" for="email">Email</label>

                        <div class="form__input-section">
                            <input type="text" id="email" name="email" class="form__input"
                                   placeholder="Куда мне писать"/>
                        </div>
                    </div>
                </div>
                <div class="form__group">
                    <label class="form__label">Сообщение</label>

                    <div class="form__input-section">
                        <textarea class="form__input" name="message"
                                  placeholder="Кратко в чем суть"></textarea>
                    </div>
                </div>
                <div class="form__group">
                    <div class="g-recaptcha" data-sitekey="6Lc-LRMTAAAAAKtSr-hc5-Kom54aaGO3pim0AM9v"></div>
                </div>
                <div class="form__footer clearfix">
                    <div class="form__col">
                        <button type="submit" class="form__btn primary">Отправить</button>
                    </div>
                    <div class="form__col">
                        <button id="clearFeedbackForm" type="reset" class="form__btn">Очистить
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>
<!-- ./напишите мне-->