<section class="section">
    <div class="section__header">
        <h2 class="section__title">Основная информация</h2>
    </div>

    <div class="section__body">
        <div class="info clearfix">
            <div class="info__photo">
                <div class="info__photo-border">
                    <div class="info__photo-wrapper">
                        <img src="img/photo.jpg" alt="It`s me" class="info__photo-img"/>
                    </div>
                </div>
            </div>

            <div class="info__body">
                <ul class="info__list">
                    <li class="info__list-item clearfix">
                        <span class="info__list-question">Меня зовут:</span>
                        <span class="info__list-response">Скрылев Александр Александрович</span>
                    </li>
                    <li class="info__list-item clearfix">
                        <span class="info__list-question">Мой возраст:</span>
                        <span class="info__list-response">24 года</span>
                    </li>
                    <li class="info__list-item clearfix">
                        <span class="info__list-question">Мой город:</span>
                        <span class="info__list-response">Майкоп, Россия</span>
                    </li>
                    <li class="info__list-item clearfix prelast">
                        <span class="info__list-question">Моя специализация:</span>
                        <span class="info__list-response">FULL STACK разработчик :D</span>
                    </li>
                    <li class="info__list-item clearfix">
                        <span class="info__list-question">Ключевые навыки:</span>
                        <span class="info__list-response">
                            <ul class="skills">
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">html</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">css</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">javascript</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">git</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">gulp</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">php</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">angular</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">python</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">jquery</span>
                                    </span>
                                </li>
                                <li class="skills_item">
                                    <span class="skills_label">
                                        <span class="skills_label-wrapper">plpgsql</span>
                                    </span>
                                </li>
                            </ul>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- ./основная информация-->

<section class="section">
    <div class="section__header">
        <h2 class="section__title">Опыт работы</h2>
    </div>

    <div class="section__body">
        <ul class="section__list">
            <li class="section__list-item">
                <div class="section__list-item-icon">
                    <span class="icon ico-case"></span>
                </div>
                <div class="section__list-item-desc">
                    Вычислительный центр ФГБОУ ВПО "АГУ" - Программист отдела сетевых технологий
                    <span class="small">Октябрь 2011 - по настоящее время</span>
                </div>
            </li>
            <li class="section__list-item">
                <div class="section__list-item-icon">
                    <span class="icon ico-case"></span>
                </div>
                <div class="section__list-item-desc">
                    "Фриланс" - frontend, backend
                    <span class="small">Август 2013 - по настоящее время</span>
                </div>
            </li>
            <li class="section__list-item">
                <div class="section__list-item-icon">
                    <span class="icon ico-case"></span>
                </div>
                <div class="section__list-item-desc">
                    "ООО Винтео" - Ведущий программист
                    <span class="small">Май 2014 - по настоящее время</span>
                </div>
            </li>
        </ul>
    </div>
</section>
<!-- ./опыт работы-->

<section class="section">
    <div class="section__header">
        <h2 class="section__title">Образование</h2>
    </div>

    <div class="section__body">
        <ul class="section__list">
            <li class="section__list-item">
                <div class="section__list-item-icon">
                    <span class="icon ico-school"></span>
                </div>
                <div class="section__list-item-desc">
                    Полное среднее. Православная гимназия Сергия Радонежского
                    <span class="small">1998 - 2008</span>
                </div>
            </li>
            <li class="section__list-item">
                <div class="section__list-item-icon">
                    <span class="icon ico-graguete"></span>
                </div>
                <div class="section__list-item-desc">
                    Высшее. Адыгейский Государственный Университет - управление и информатика в
                    технических системах
                    <span class="small">Сентябрь 2008 - Июнь 2013</span>
                </div>
            </li>
            <li class="section__list-item">
                <div class="section__list-item-icon">
                    <span class="icon ico-diploma"></span>
                </div>
                <div class="section__list-item-desc">
                    Курсы Loftschool.ru
                    <span class="small">Ноябрь 2015 - по настоящее время</span>
                </div>
            </li>
        </ul>
    </div>
</section>
<!-- ./образование-->