<!--build:js js/vendor.min.js-->
<script src="/bower/jquery/dist/jquery.min.js"></script>
<!--endbuild-->
<!--build:js js/main.min.js-->
<script src="/js/skValidator.js"></script>
<script src="/js/skModal.js"></script>
<script src="/js/main.js"></script>
<!--endbuild-->

<?php $currentPage = \Skaynetmen\Homework1\Core\Url::get(); ?>

<?php if ($currentPage == '/works' || $currentPage == '/feedback'): ?>
    <!--build:js js/vendor.ie.min.js-->
    <!--[if lt IE 9]>
    <script src="/bower/jquery-placeholder/jquery.placeholder.min.js"></script>
    <![endif]-->
    <!--endbuild-->
<?php endif; ?>
<?php if ($currentPage == '/works'): ?>
    <!--build:js js/works.min.js-->
    <script src="/bower/blueimp-file-upload/js/vendor/jquery.ui.widget.js"></script>
    <script src="/bower/blueimp-file-upload/js/jquery.iframe-transport.js"></script>
    <script src="/bower/blueimp-file-upload/js/jquery.fileupload.js"></script>
    <script src="/js/works.js"></script>
    <!--endbuild-->
<?php endif; ?>
<?php if ($currentPage == '/feedback'): ?>
    <script src="//www.google.com/recaptcha/api.js"></script>
    <!--build:js js/feedback.min.js-->
    <script src="/js/feedback.js"></script>
    <!--endbuild-->
<?php endif; ?>
<?php if ($currentPage == '/auth'): ?>
    <!--build:js js/auth.min.js-->
    <script src="/js/auth.js"></script>
    <!--endbuild-->
<?php endif; ?>
