<section class="section">
    <div class="section__header">
        <h1 class="section__title">Мои работы</h1>
    </div>

    <div class="section__body">
        <div id="works" class="works">
            <ul class="works__list">
                <?php foreach ($this->works as $work): ?>
                    <li class="works__item">
                        <a href="<?php echo $work->link; ?>" class="work">
                            <div class="work__preview">
                                <img src="<?php echo $work->image; ?>" alt="<?php echo $work->title; ?>"
                                     class="work__img"/>
                                                <span class="work__hover">
                                                    <span class="work__hover-title">Подробнее</span>
                                                </span>
                            </div>
                            <h4 class="work__title"><?php echo $work->title; ?></h4>

                            <div class="work__desc">
                                <p><?php echo $work->description; ?></p>
                            </div>
                        </a>
                    </li>
                <?php endforeach; ?>
                <?php if (\Skaynetmen\Homework1\Core\Auth::loggedIn()): ?>
                <li class="works__item">
                    <a id="addWork" href="#" class="work add">
                        <div class="work__add-img">
                            <span class="icon ico-pic"></span>
                        </div>
                        <h4 class="work__add-title">Добавить работу</h4>
                    </a>
                </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</section>
<!-- ./мои работы-->

<?php if (\Skaynetmen\Homework1\Core\Auth::loggedIn()): ?>
<div id="modalAddWork" class="modal">
    <div class="modal__wrapper">
        <h4 class="modal__title">Добавление проекта</h4>

        <div class="modal__body">
            <button class="modal__close">&times;</button>
            <div id="modalMsg"></div>
            <form id="formAddWork" action="/works/add" method="post" enctype="multipart/form-data">
                <div class="form__group">
                    <label for="projectName" class="form__label">Название проекта</label>

                    <div class="form__input-section">
                        <input type="text" id="projectName" name="name" class="form__input"
                               placeholder="Введите название"/>
                    </div>
                </div>
                <div class="form__group">
                    <label for="projectImg" class="form__label">Картинка проекта</label>

                    <div class="form__input-section">
                        <input type="file" id="projectImg" name="files[]" class="hidden"/>

                        <div class="form__input-group">
                            <input type="text" id="fakeProjectImg" name="img" class="form__input"
                                   placeholder="Загрузите изображение" readonly/>
                                <span class="form__input-group-btn">
                                    <button id="fakeInputFile" type="button" class="form__btn"><i
                                            class="icon ico-cloud"></i></button>
                                </span>
                        </div>
                    </div>
                    <div id="imgThumbnail" class="files"></div>
                </div>
                <div class="form__group">
                    <label for="projectUrl" class="form__label">URL проекта</label>

                    <div class="form__input-section">
                        <input type="text" id="projectUrl" name="url" class="form__input"
                               placeholder="Добавьте ссылку"/>
                    </div>
                </div>
                <div class="form__group">
                    <label for="projectDesc" class="form__label">Описание</label>

                    <div class="form__input-section">
                            <textarea id="projectDesc" name="desc" class="form__input"
                                      placeholder="Пара слов"></textarea>
                    </div>
                </div>
                <div class="form__footer">
                    <button type="submit" class="form__btn primary">Добавить</button>
                </div>
            </form>
        </div>
    </div>
</div>
<?php endif; ?>