<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="ru-RU"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title><?php echo $this->title; ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content=""/>
    <meta name="keywords" content=""/>
    <meta name="author" content=""/>
    <meta name="copyright" content="">
    <meta http-equiv="Reply-to" content="">

    <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png"/>
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"/>
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png"/>
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"/>
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png"/>
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"/>
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png"/>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"/>
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png"/>
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon.png"/>
    <?php \Skaynetmen\Homework1\Core\View::includePartial('partials/stylesheets.phtml'); ?>
</head>
<body class="bg">
<div class="wrapper">
    <header id="header" class="header">
        <div class="container big">
            <div class="logo">
                <a href="./" class="logo__link">
                    <img src="img/logo.png" alt="Loftschool" class="logo__img"/>
                </a>
            </div>

            <div class="socials">
                <ul class="socials__list">
                    <li class="socials__item">
                        <a href="https://www.facebook.com/apt.get.remove" class="socials__link icon ico-facebook"
                           target="_blank"> facebook </a>
                    </li>
                    <li class="socials__item">
                        <a href="https://vk.com/sk.avenger" class="socials__link icon ico-vk" target="_blank">vk</a>
                    </li>
                    <li class="socials__item">
                        <a href="https://twitter.com/Sk_Avenger" class="socials__link icon ico-twitter"
                           target="_blank">twitter</a>
                    </li>
                    <li class="socials__item">
                        <a href="https://github.com/skaynetmen" class="socials__link icon ico-github"
                           target="_blank">github</a>
                    </li>
                </ul>
            </div>

            <div id="mobileMenu" class="mobile-menu">
                <span class="mobile-menu__line"></span>
                <span class="mobile-menu__line"></span>
                <span class="mobile-menu__line"></span>
            </div>
        </div>
    </header>
    <?php $this->requirePartial('partials/main.phtml'); ?>
</div>
<footer class="footer">
    <div class="container clearfix">
        <div class="login">
            <a href="/auth" class="login__link">
                <span class="icon ico-locked"></span>
                вход
            </a>
        </div>
        <div class="copyright">
            <p>&copy; 2015. Это мой сайт, пожалуйста, не копируйте и не воруйте его!</p>
        </div>
    </div>
</footer>
<?php \Skaynetmen\Homework1\Core\View::includePartial('partials/scripts.phtml'); ?>
</body>
</html>