<section class="section">
    <div class="section__header">
        <h2 class="section__title">Админка</h2>
    </div>

    <div class="section__body">
        <div id="admin" class="admin">
            <h3 class="admin__title">Работы</h3>
            <table class="admin__table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Название</th>
                    <th>Дата создания</th>
                    <th>Дата редактирования</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->works as $work): ?>
                    <tr>
                        <td><?php echo $work->id; ?></td>
                        <td><?php echo $work->title; ?></td>
                        <td><?php echo date('H:i d.m.Y', $work->created_at); ?></td>
                        <td><?php echo date('H:i d.m.Y', $work->updated_at); ?></td>
                        <td>
                            <a href="/admin/work/<?php echo $work->id; ?>" class="admin__edit">Редактировать</a>
                            <a href="#" class="admin__delete">Удалить</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>

            <h3 class="admin__title">Пользователи</h3>
            <table class="admin__table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Email</th>
                    <th>Дата создания</th>
                    <th>Дата редактирования</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($this->users as $user): ?>
                    <tr>
                        <td><?php echo $user->id; ?></td>
                        <td><?php echo $user->email; ?></td>
                        <td><?php echo date('H:i d.m.Y', $user->created_at); ?></td>
                        <td><?php echo date('H:i d.m.Y', $user->updated_at); ?></td>
                        <td>
                            <a href="/admin/user/<?php echo $user->id; ?>" class="admin__edit">Редактировать</a>
                            <a href="#" class="admin__delete">Удалить</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</section>